"""1st change

Revision ID: 3ce16975f759
Revises: 
Create Date: 2025-08-28 21:22:25.298908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce16975f759'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_creator_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('registrations_event_id_fkey'), 'registrations', type_='foreignkey')
    op.drop_constraint(op.f('registrations_user_id_fkey'), 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'registrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key(op.f('registrations_user_id_fkey'), 'registrations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('registrations_event_id_fkey'), 'registrations', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_creator_id_fkey'), 'events', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###
